debug: false

messages:
  prefix: "§6[§fCannons§bRPG§6]§f "
  storm_blast: "§7Storm Blast is now %s"
  double_shot: "Double shot activated!"

cooldowns:
  gunpowder_leveler: 10
  aiming_leveler: 30
  firing_leveler: 5
  damage_leveler: 0
  kill_leveler: 0